# Generated by Django 5.0.3 on 2024-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cookbook', '0002_recipe_ingredients_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
